version: "3.9"
services:    
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        container_name: messaging
        ports:
            - 5672:5672
            - 15672:15672
        networks: 
            - realnet
    
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
        ports:
        - "1433:1433"
        environment:
            # SA_PASSWORD: "myP@ss123"
            # ACCEPT_EULA: "Y"
            - SA_PASSWORD=${SA_PASSWORD}
            - ACCEPT_EULA=${ACCEPT_EULA}
            - MSSQL_PID=Developer
        volumes:
            # - C:\MSSQL\DockerFiles\system:/var/opt/mssql/data
            - ./mssql/data:/var/opt/mssql/data
        networks: 
            - realnet        
    
#volumes:
    #data:
    
networks: 
    realnet:
        driver: bridge
    
